### ISSUE TITLE
Error: could not obtain a database connection within 5.000 seconds (waited 5.001 seconds)

### ISSUE THREAD

**Issue by poorva29** [gilmour-libs/gilmour#29]
We have a subscriber which is running , below is the stacktrace.
This happens when you register a key with `slot <data>, <key>` and then send signal!
This error occurs at random , after sending 'n' signals to slot
Not aware of correct steps to reproduce.

`
"/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:190:in block in wait_poll'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in loop'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in wait_poll'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:136:in block in poll'", "/home/poorva/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/monitor.rb:211:in mon_synchronize'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:146:in synchronize'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:134:in poll'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:423:in acquire_connection'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:356:in block in checkout'", "/home/poorva/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/monitor.rb:211:in mon_synchronize'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:355:in checkout'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in block in connection'", "/home/poorva/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/monitor.rb:211:in mon_synchronize'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in connection'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:546:in retrieve_connection'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/connection_handling.rb:79:in retrieve_connection'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/connection_handling.rb:53:in connection'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/relation/delegation.rb:14:in connection'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/relation/finder_methods.rb:279:in find_one'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/relation/finder_methods.rb:268:in find_with_ids'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/relation/finder_methods.rb:35:in find'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-deprecated_finders-1.0.3/lib/active_record/deprecated_finders/relation.rb:122:in find'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.0/lib/active_record/querying.rb:3:in find'", "/home/poorva/tuts-rails/microservices/tripdata/subscribers/populate_data_for_trip.rb:65:in block in <class:PopulateDataForTrip>'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/bundler/gems/gilmour-98cb1360b56d/lib/gilmour/responder.rb:295:in instance_eval'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/bundler/gems/gilmour-98cb1360b56d/lib/gilmour/responder.rb:295:in block in _execute'", "/home/poorva/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/timeout.rb:66:in timeout'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/bundler/gems/gilmour-98cb1360b56d/lib/gilmour/responder.rb:294:in _execute'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/bundler/gems/gilmour-98cb1360b56d/lib/gilmour/responder.rb:205:in execute'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/bundler/gems/gilmour-98cb1360b56d/lib/gilmour/backends/backend.rb:244:in _execute_handler'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/bundler/gems/gilmour-98cb1360b56d/lib/gilmour/backends/backend.rb:228:in execute_handler'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/bundler/gems/gilmour-98cb1360b56d/lib/gilmour/backends/redis.rb:113:in block (2 levels) in pmessage_handler'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in call'", "/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in block in spawn_threadpool
`

**Comment by adityagodbole** [comment]
This bug is not in the gilmour code at all. It is in some activerecord code that is being used.
