### ISSUE TITLE
Subscribers to redis are not activated when `true` parameter for `listen_to` is used

### ISSUE THREAD

**Issue by poorva29** [gilmour-libs/gilmour#6]
When doing - 
`listen_to 'my_message'` and passing a parameter `true`, 
i cannot see subscribers for it on redis.
"subscribe" "my_message"

after publishing a message - 
`publish  'my_message', <some_data>`

the subscribers are not activated

**Comment by poorva29** [comment]
We upgraded redis-server version to, 
Redis server v=2.8.19 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=a789ed9377dc12b9

After which all services started working as expected.

**Comment by adityagodbole** [comment]
Closing this issue

**Comment by poorva29** [comment]
Same behaviour is reproduced, reopening the same issue

**Comment by adityagodbole** [comment]
Can you provide detailed steps to reproduce this issue? Include all
versions, shas and stacktrace information.
